# Generated by Django 5.1.4 on 2024-12-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='size',
            field=models.CharField(choices=[('1', 'Single one'), ('3', 'Family')], default='1', max_length=10),
        ),
    ]
