# Generated by Django 5.1.4 on 2025-01-20 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_comment_pizza_sandwich_delete_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='object_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='foods.pizza'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='sandwich',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='foods.sandwich'),
            preserve_default=False,
        ),
    ]
