# Generated by Django 5.1.4 on 2025-01-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_sandwich_rename_food_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='short_description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sandwich',
            name='short_description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
