# Generated by Django 5.1.4 on 2025-01-21 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_remove_comment_content_type_remove_comment_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='foods.pizza'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sandwich',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='foods.sandwich'),
        ),
    ]
