# Generated by Django 5.1.4 on 2025-01-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_pizza_short_description_sandwich_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
