# Generated by Django 5.1.4 on 2025-01-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_alter_comment_pizza_alter_comment_sandwich'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/profile_cover'),
        ),
    ]
