# Generated by Django 5.1.4 on 2025-01-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_comment_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
