# Generated by Django 5.1.4 on 2025-01-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_remove_comment_content_type_remove_comment_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile/profile_cover'),
        ),
    ]
