# Generated by Django 5.1.4 on 2025-01-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_comment_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, upload_to='pizza/pizza_cover'),
        ),
        migrations.AddField(
            model_name='sandwich',
            name='image',
            field=models.ImageField(blank=True, upload_to='sandwich/sandwich_cover'),
        ),
    ]
